export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST'
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS'
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE'

export const SEND_USER_INPUT = 'SEND_USER_INPUT'
export const SEND_FILTERED_CITY_REDUCER = 'SEND_FILTERED_CITY_REDUCER'
export const SEND_CITYNAME = 'SEND_CITYNAME'