export const POST_FAVOURITES_SUCCESS = "POST_FAVOURITES_SUCCESS";
export const POST_FAVOURITES_FAILURE = "POST_FAVOURITES_FAILURE";

export const DELETE_FAVOURITES_SUCCESS = "DELETE_FAVOURITES_SUCCESS";
export const DELETE_FAVOURITES_FAILURE = "DELETE_FAVOURITES_FAILURE";

export const FETCH_FAVOURITES_REQUEST = "FETCH_FAVOURITES_REQUEST";
export const FETCH_FAVOURITES_SUCCESS = "FETCH_FAVOURITES_SUCCESS";
export const FETCH_FAVOURITES_FAILURE = "FETCH_FAVOURITES_FAILURE";

export const FETCH_FAVOURITES_PAGE_REQUEST = "FETCH_FAVOURITES_PAGE_REQUEST";
export const FETCH_FAVOURITES_PAGE_SUCCESS = "FETCH_FAVOURITES_PAGE_SUCCESS";
export const FETCH_FAVOURITES_PAGE_FAILURE = "FETCH_FAVOURITES_PAGE_FAILURE";
