export const FETCH_ITINERARIES_REQUEST = "FETCH_ITINERARIES_REQUEST";
export const FETCH_ITINERARIES_SUCCESS = "FETCH_ITINERARIES_SUCCESS";
export const FETCH_ITINERARIES_FAILURE = "FETCH_ITINERARIES_FAILURE";

export const DECREASE_ITINERARIES_COUNT_REQUEST =
  "DECREASE_ITINERARIES_COUNT_REQUEST ";
export const DECREASE_ITINERARIES_COUNT_SUCCESS =
  "DECREASE_ITINERARIES_COUNT_SUCCESS";
export const DECREASE_ITINERARIES_COUNT_FAILURE =
  "DECREASE_ITINERARIES_COUNT_FAILURE";

export const INCREASE_ITINERARIES_COUNT_REQUEST =
  "INCREASE_ITINERARIES_COUNT_REQUEST ";
export const INCREASE_ITINERARIES_COUNT_SUCCESS =
  "INCREASE_ITINERARIES_COUNT_SUCCESS";
export const INCREASE_ITINERARIES_COUNT_FAILURE =
  "INCREASE_ITINERARIES_COUNT_FAILURE";
